In [1]:
import numpy as np
a = np.random.randn(5)

In [2]:
display(a)

array([-0.07046691,  0.98033854, -0.787017  , -0.77132252,  3.10192434])

In [3]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.07046691  0.98033854 -0.787017   -0.77132252  3.10192434]


In [6]:
print(np.dot(a,a.T))

11.802298039369596


In [8]:
a = np.random.randn(5,1)

In [9]:
display(a)

array([[0.9288838 ],
       [0.60207963],
       [0.3150397 ],
       [0.72657763],
       [1.66036213]])

In [10]:
display(a.T)

array([[0.9288838 , 0.60207963, 0.3150397 , 0.72657763, 1.66036213]])

In [12]:
display(np.dot(a, a.T))

array([[0.86282511, 0.55926202, 0.29263527, 0.67490619, 1.54228348],
       [0.55926202, 0.36249989, 0.18967899, 0.43745759, 0.99967022],
       [0.29263527, 0.18967899, 0.09925001, 0.2289008 , 0.52307998],
       [0.67490619, 0.43745759, 0.2289008 , 0.52791505, 1.20638198],
       [1.54228348, 0.99967022, 0.52307998, 1.20638198, 2.7568024 ]])

In [13]:
x=np.array([[[1],[2]],[[3],[4]]])
x

array([[[1],
        [2]],

       [[3],
        [4]]])

In [24]:
a = np.random.randn(3,4) # a.shape=(3,3)a.shape=(3,3)

b = np.random.randn(1, 4) # b.shape=(2,1)b.shape=(2,1)

c = a+b
c

array([[ 0.22030509, -0.36506129,  2.13064187, -1.09757474],
       [-2.19604048,  1.96885314,  1.19995376, -0.44386819],
       [-0.30770202, -1.24618628,  2.86698585, -0.42444088]])

In [17]:
a = np.random.randn(4,3) # a.shape=(4,3)a.shape=(4,3)

b = np.random.randn(3,2) # b.shape=(3,2)b.shape=(3,2)

c = a * b 

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [19]:
a=np.random.randn(12288,150) 

# a.shape=(12288,150)a.shape=(12288,150)

b=np.random.randn(150,45) 

# b.shape=(150,45)b.shape=(150,45)

c=np.dot(a,b)
c.shape

(12288, 45)

In [22]:
a=np.array([[1, 1], [1, -1]])

b=np.array([[2],[3]])

c=a+b
c

array([[3, 3],
       [4, 2]])

In [25]:
a = np.array([[2, 1], [1, 3]])
a * a

array([[4, 1],
       [1, 9]])

In [27]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a * b
c

array([[-0.09127331,  0.02406025, -0.22842519],
       [-0.08446877,  0.16787161, -0.04561861],
       [ 2.01290038, -1.1532467 ,  0.49695841]])