In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
a = np.random.rand(1_000_000)
b = np.random.rand(1_000_000)

In [5]:
%%time
c = np.dot(a, b)
display(c)

250173.9171355766

CPU times: total: 0 ns
Wall time: 2 ms


In [6]:
%%time
c = 0
for i in range(1_000_000):
    c +=  a[i] * b[i]
display(c)

250173.91713558324

CPU times: total: 15.6 ms
Wall time: 148 ms


In [25]:
arr = np.array([
    [
        [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3], [4, 5, 6]]
    ],
    [
        [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3], [4, 5, 6]]
    ]
])
arr.shape

(2, 3, 3, 3)

In [30]:
arr_flat = arr.reshape(arr.shape[0], -1).T
arr_flat

array([[1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [31]:
arr_flat / 6

array([[0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.16666667, 0.16666667],
       [0.33333333, 0.33333333],
       [0.5       , 0.5       ],
       [0.66666667, 0.66666667],
       [0.83333333, 0.83333333],
       [1.        , 1.        ]])

In [32]:
-(0 * np.log(0.5) + (1 - 0) * np.log(1 - 0.5))

0.6931471805599453